# Generated by Django 3.1.7 on 2021-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210421_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
    ]
