# Generated by Django 3.2 on 2021-04-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_signup_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('time_slot', models.CharField(max_length=200)),
                ('table_no', models.CharField(max_length=255)),
                ('table_type', models.CharField(max_length=255)),
                ('guest_no', models.CharField(max_length=122)),
            ],
        ),
    ]
