# Generated by Django 3.2 on 2021-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_book_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='date',
            field=models.DateField(max_length=255),
        ),
    ]
