# Generated by Django 3.2 on 2021-04-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_book_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_table',
            name='date',
        ),
    ]
