# Generated by Django 3.2 on 2021-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_book_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_table',
            name='date',
        ),
        migrations.AddField(
            model_name='book_table',
            name='Date_coming',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
