# Generated by Django 3.2 on 2021-04-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210424_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Now',
        ),
    ]
