# Generated by Django 3.1.7 on 2021-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_delete_order_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='guest_no',
            field=models.IntegerField(max_length=122),
        ),
        migrations.AlterField(
            model_name='book_table',
            name='table_no',
            field=models.IntegerField(max_length=255),
        ),
    ]
