# Generated by Django 3.2 on 2021-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_book_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='date',
            field=models.DateField(),
            
        ),
    ]
