# Generated by Django 3.2 on 2021-04-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_book_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=220)),
                ('Order_Snacks', models.CharField(max_length=255, null=True)),
                ('Order_lunch', models.CharField(max_length=255, null=True)),
                ('Order_Beverages', models.CharField(max_length=200, null=True)),
                ('date_order', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='book_table',
            name='date',
            field=models.DateField(max_length=255),
        ),
    ]
