# Generated by Django 3.2 on 2021-04-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20210424_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='Img',
            field=models.ImageField(default=0, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
