# Generated by Django 3.2 on 2021-04-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_order_now_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='Img',
            field=models.URLField(),
        ),
    ]
