# Generated by Django 3.2 on 2021-04-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_order_now_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_now',
            old_name='Img',
            new_name='image',
        ),
    ]
