# Generated by Django 3.2 on 2021-04-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_rename_img_order_now_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_now',
            name='Order_Beverages',
        ),
        migrations.RemoveField(
            model_name='order_now',
            name='Order_Snacks',
        ),
        migrations.RemoveField(
            model_name='order_now',
            name='Order_lunch',
        ),
        migrations.RemoveField(
            model_name='order_now',
            name='date_order',
        ),
        migrations.RemoveField(
            model_name='order_now',
            name='gmail',
        ),
    ]
