# Generated by Django 3.2 on 2021-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20210424_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_now',
            name='Order_Beverages',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order_now',
            name='Order_Snacks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_now',
            name='Order_lunch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_now',
            name='date_order',
            field=models.DateField(),
            
        ),
        migrations.AddField(
            model_name='order_now',
            name='gmail',
            field=models.EmailField( max_length=220),
            
        ),
    ]
