# Generated by Django 3.2 on 2021-04-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20210424_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='Order_lunch',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
