# Generated by Django 3.2 on 2021-04-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_order_now_order_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='date_order',
            field=models.DateField(),
            
        ),
    ]
