# Generated by Django 3.2 on 2021-04-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_order_now_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_now',
            name='date_order',
        ),
        migrations.AlterField(
            model_name='order_now',
            name='Order_Beverages',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_now',
            name='Order_Snacks',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
