# Generated by Django 3.2 on 2021-04-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20210424_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_now',
            name='date',
            field=models.DateField(max_length=255),
            preserve_default=False,
            
            
        ),
    ]
