# Generated by Django 3.2 on 2021-04-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_order_now_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_now',
            old_name='date',
            new_name='date1',
        ),
    ]
