# Generated by Django 3.2 on 2021-04-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_order_now_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_now',
            name='date1',
        ),
    ]
