# Generated by Django 3.1.7 on 2021-04-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_order_now_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
