# Generated by Django 3.1.7 on 2021-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_auto_20210424_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
