# Generated by Django 3.1.7 on 2021-04-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_auto_20210424_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_now',
            old_name='date',
            new_name='date1',
        ),
    ]
