# Generated by Django 3.1.7 on 2021-04-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_auto_20210424_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_now',
            name='date1',
        ),
    ]
