# Generated by Django 3.1.7 on 2021-04-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_remove_order_now_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_now',
            name='date1',
            field=models.DateField(max_length=255),
            preserve_default=False,
        ),
    ]
