# Generated by Django 3.1.7 on 2021-04-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_book_table_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_now',
            name='takeaway',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
