# Generated by Django 3.2 on 2021-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_auto_20210425_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_now',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
