# Generated by Django 3.1.7 on 2021-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_order_now_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_now',
            name='order_id',
            field=models.IntegerField(unique=True),
        ),
    ]
