# Generated by Django 3.1.7 on 2021-04-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_order_now_distance_from_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_now',
            old_name='takeaway',
            new_name='Delivery',
        ),
    ]
